-- Single source of truth for all workstation keybindings and shortcuts.
-- Both Hyprland session registration (keybind.lua) and user-facing Hotkeys help
-- (workstation-hotkeys) are dynamically derived from this manifest.

local M = {}

M.mainMod = "SUPER"
M.terminal = "kitty"
M.explorer = "thunar"

M.categories = {
    "Applications & Launchers",
    "Window Management",
    "Window Focus & Resizing",
    "Workspaces",
    "Mouse Controls",
    "Audio & Media Controls",
}

M.bindings = {
    -- Applications & Launchers
    {
        id = "terminal",
        category = "Applications & Launchers",
        key = "SUPER + RETURN",
        action_type = "exec",
        command = M.terminal,
        desktop_id = "kitty.desktop",
        display_key = "SUPER + RETURN",
        description = "Open Terminal (" .. M.terminal .. ")",
        runnable = true,
    },
    {
        id = "file_manager",
        category = "Applications & Launchers",
        key = "SUPER + E",
        action_type = "exec",
        command = M.explorer,
        desktop_id = "thunar.desktop",
        display_key = "SUPER + E",
        description = "Open File Manager (" .. M.explorer .. ")",
        runnable = true,
    },
    {
        id = "launcher",
        category = "Applications & Launchers",
        key = "SUPER + D",
        action_type = "exec",
        command = "noctalia msg panel-toggle launcher",
        desktop_id = "dev.noctalia.Noctalia.desktop",
        display_key = "SUPER + D",
        description = "Open Application Launcher",
        runnable = true,
    },
    {
        id = "hotkeys",
        category = "Applications & Launchers",
        key = "SUPER + K",
        action_type = "exec",
        command = "workstation-hotkeys",
        desktop_id = "workstation-hotkeys.desktop",
        display_key = "SUPER + K",
        description = "Open this Hotkeys Reference",
        runnable = true,
    },
    {
        id = "desktop_settings",
        category = "Applications & Launchers",
        key = "SUPER + T",
        action_type = "exec",
        command = "noctalia msg settings-toggle",
        desktop_id = "dev.noctalia.Noctalia.desktop",
        display_key = "SUPER + T",
        description = "Open Desktop Settings",
        runnable = true,
    },
    {
        id = "lock_screen",
        category = "Applications & Launchers",
        key = "SUPER + L",
        action_type = "exec",
        command = "noctalia msg screen-lock",
        display_key = "SUPER + L",
        description = "Lock Screen",
        runnable = true,
    },

    -- Window Management
    {
        id = "window_close",
        category = "Window Management",
        key = "SUPER + Q",
        action_type = "dispatch_close",
        display_key = "SUPER + Q",
        description = "Close Active Window",
        runnable = false,
    },
    {
        id = "window_toggle_float",
        category = "Window Management",
        key = "SUPER + W",
        action_type = "dispatch_float",
        display_key = "SUPER + W",
        description = "Toggle Floating Window",
        runnable = false,
    },
    {
        id = "window_toggle_fullscreen",
        category = "Window Management",
        key = "SUPER + F",
        action_type = "dispatch_fullscreen",
        display_key = "SUPER + F",
        description = "Toggle Fullscreen Window",
        runnable = false,
    },
    {
        id = "window_cycle_focus",
        category = "Window Management",
        key = "ALT + tab",
        action_type = "dispatch_cycle",
        display_key = "ALT + Tab",
        description = "Cycle Window Focus",
        runnable = false,
    },

    -- Window Focus & Resizing
    {
        id = "focus_left",
        category = "Window Focus & Resizing",
        key = "SUPER + left",
        action_type = "focus",
        direction = "left",
        display_key = "SUPER + Left",
        description = "Focus Left Window",
        runnable = false,
    },
    {
        id = "focus_right",
        category = "Window Focus & Resizing",
        key = "SUPER + right",
        action_type = "focus",
        direction = "right",
        display_key = "SUPER + Right",
        description = "Focus Right Window",
        runnable = false,
    },
    {
        id = "focus_up",
        category = "Window Focus & Resizing",
        key = "SUPER + up",
        action_type = "focus",
        direction = "up",
        display_key = "SUPER + Up",
        description = "Focus Up Window",
        runnable = false,
    },
    {
        id = "focus_down",
        category = "Window Focus & Resizing",
        key = "SUPER + down",
        action_type = "focus",
        direction = "down",
        display_key = "SUPER + Down",
        description = "Focus Down Window",
        runnable = false,
    },
    {
        id = "resize_window_left",
        category = "Window Focus & Resizing",
        key = "SUPER + SHIFT + left",
        action_type = "exec_resize",
        resize_args = "-30 0",
        display_key = "SUPER + SHIFT + Left",
        description = "Resize Active Window Left (-30px)",
        runnable = false,
    },
    {
        id = "resize_window_right",
        category = "Window Focus & Resizing",
        key = "SUPER + SHIFT + right",
        action_type = "exec_resize",
        resize_args = "30 0",
        display_key = "SUPER + SHIFT + Right",
        description = "Resize Active Window Right (+30px)",
        runnable = false,
    },
    {
        id = "resize_window_up",
        category = "Window Focus & Resizing",
        key = "SUPER + SHIFT + up",
        action_type = "exec_resize",
        resize_args = "0 -30",
        display_key = "SUPER + SHIFT + Up",
        description = "Resize Active Window Up (-30px)",
        runnable = false,
    },
    {
        id = "resize_window_down",
        category = "Window Focus & Resizing",
        key = "SUPER + SHIFT + down",
        action_type = "exec_resize",
        resize_args = "0 30",
        display_key = "SUPER + SHIFT + Down",
        description = "Resize Active Window Down (+30px)",
        runnable = false,
    },

    -- Workspaces
    {
        id = "workspaces_switch_1_10",
        category = "Workspaces",
        generator = "workspaces_1_10",
        display_key = "SUPER + 1 .. 9, 0",
        description = "Switch to Workspace 1–10",
        runnable = false,
    },
    {
        id = "workspaces_move_1_10",
        category = "Workspaces",
        generator = "workspaces_move_1_10",
        display_key = "SUPER + SHIFT + 1 .. 9, 0",
        description = "Move Window to Workspace 1–10",
        runnable = false,
    },
    {
        id = "workspace_prev",
        category = "Workspaces",
        key = "SUPER + CTRL + left",
        action_type = "focus_workspace_relative",
        workspace = "r-1",
        display_key = "SUPER + CTRL + Left",
        description = "Previous Workspace",
        runnable = false,
    },
    {
        id = "workspace_next",
        category = "Workspaces",
        key = "SUPER + CTRL + right",
        action_type = "focus_workspace_relative",
        workspace = "r+1",
        display_key = "SUPER + CTRL + Right",
        description = "Next Workspace",
        runnable = false,
    },
    {
        id = "workspace_touchpad_swipe",
        category = "Workspaces",
        action_type = "gesture",
        display_key = "3-Finger Horizontal Swipe",
        description = "Switch Workspaces (Touchpad)",
        runnable = false,
    },

    -- Mouse Controls
    {
        id = "mouse_window_drag",
        category = "Mouse Controls",
        key = "SUPER + mouse:272",
        action_type = "mouse_drag",
        mouse = true,
        display_key = "SUPER + Left Mouse Drag",
        description = "Move Floating Window",
        runnable = false,
    },
    {
        id = "mouse_window_resize",
        category = "Mouse Controls",
        key = "SUPER + mouse:273",
        action_type = "mouse_resize",
        mouse = true,
        display_key = "SUPER + Right Mouse Drag",
        description = "Resize Floating Window",
        runnable = false,
    },

    -- Audio & Media Controls
    {
        id = "media_play_pause",
        category = "Audio & Media Controls",
        key = "XF86AudioPlay",
        action_type = "exec_locked",
        command = "playerctl play-pause",
        display_key = "Play / Pause Key",
        description = "Toggle Play / Pause (playerctl)",
        runnable = true,
    },
    {
        id = "media_next_track",
        category = "Audio & Media Controls",
        key = "XF86AudioNext",
        action_type = "exec_locked",
        command = "playerctl next",
        display_key = "Next Track Key",
        description = "Next Track (playerctl)",
        runnable = true,
    },
    {
        id = "media_prev_track",
        category = "Audio & Media Controls",
        key = "XF86AudioPrev",
        action_type = "exec_locked",
        command = "playerctl previous",
        display_key = "Previous Track Key",
        description = "Previous Track (playerctl)",
        runnable = true,
    },
    {
        id = "volume_raise",
        category = "Audio & Media Controls",
        key = "XF86AudioRaiseVolume",
        action_type = "exec_locked",
        command = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+",
        display_key = "Volume Up Key",
        description = "Adjust Volume Up 5% (wpctl)",
        runnable = true,
    },
    {
        id = "volume_lower",
        category = "Audio & Media Controls",
        key = "XF86AudioLowerVolume",
        action_type = "exec_locked",
        command = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-",
        display_key = "Volume Down Key",
        description = "Adjust Volume Down 5% (wpctl)",
        runnable = true,
    },
    {
        id = "volume_mute_toggle",
        category = "Audio & Media Controls",
        key = "XF86AudioMute",
        action_type = "exec_locked",
        command = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
        display_key = "Mute Key",
        description = "Toggle Audio Mute (wpctl)",
        runnable = true,
    },
}

return M
