-- Single source of truth for all workstation keybindings and shortcuts.
-- Both Hyprland session registration (keybind.lua) and user-facing Hotkeys help
-- (workstation-hotkeys) are dynamically derived from this manifest.

local M = {}

M.mainMod = "SUPER"
M.terminal = "kitty"
M.explorer = "thunar"

M.categories = {
    "Applications & Launchers",
    "Window Management",
    "Workspaces",
    "Window Focus & Resizing",
    "Audio & Media Controls",
    "Mouse Controls",
}

M.bindings = {
    -- Applications & Launchers
    {
        id = "launcher",
        priority = 10,
        editable = true,
        category = "Applications & Launchers",
        key = "SUPER + D",
        action_type = "exec",
        command = "noctalia msg panel-toggle launcher",
        command_argv = { "noctalia", "msg", "panel-toggle", "launcher" },
        desktop_id = "dev.noctalia.Noctalia.desktop",
        display_key = "Super + D",
        description = "App Launcher",
        runnable = true,
    },
    {
        id = "terminal",
        priority = 20,
        editable = true,
        category = "Applications & Launchers",
        key = "SUPER + RETURN",
        action_type = "exec",
        command = M.terminal,
        command_argv = { M.terminal },
        desktop_id = "kitty.desktop",
        display_key = "Super + Return",
        description = "Terminal",
        runnable = true,
    },
    {
        id = "file_manager",
        priority = 30,
        editable = true,
        category = "Applications & Launchers",
        key = "SUPER + E",
        action_type = "exec",
        command = M.explorer,
        command_argv = { M.explorer },
        desktop_id = "thunar.desktop",
        display_key = "Super + E",
        description = "Files",
        runnable = true,
    },
    {
        id = "hotkeys",
        priority = 50,
        editable = true,
        category = "Applications & Launchers",
        key = "SUPER + K",
        action_type = "exec",
        command = "workstation-hotkeys",
        command_argv = { "workstation-hotkeys" },
        desktop_id = "workstation-hotkeys.desktop",
        display_key = "Super + K",
        description = "Hotkeys",
        runnable = true,
    },
    {
        id = "desktop_settings",
        priority = 60,
        editable = true,
        category = "Applications & Launchers",
        key = "SUPER + T",
        action_type = "exec",
        command = "noctalia msg settings-toggle",
        command_argv = { "noctalia", "msg", "settings-toggle" },
        desktop_id = "dev.noctalia.Noctalia.desktop",
        display_key = "Super + T",
        description = "Desktop Settings",
        runnable = true,
    },
    {
        id = "lock_screen",
        priority = 70,
        editable = true,
        category = "Applications & Launchers",
        key = "SUPER + L",
        action_type = "exec",
        command = "noctalia msg screen-lock",
        command_argv = { "noctalia", "msg", "screen-lock" },
        display_key = "Super + L",
        description = "Lock Screen",
        runnable = true,
    },

    -- Window Management
    {
        id = "window_close",
        priority = 100,
        editable = true,
        category = "Window Management",
        key = "SUPER + Q",
        action_type = "dispatch_close",
        display_key = "Super + Q",
        description = "Close Window",
        runnable = false,
    },
    {
        id = "window_toggle_fullscreen",
        priority = 110,
        editable = true,
        category = "Window Management",
        key = "SUPER + F",
        action_type = "dispatch_fullscreen",
        display_key = "Super + F",
        description = "Fullscreen",
        runnable = false,
    },
    {
        id = "window_toggle_float",
        priority = 120,
        editable = true,
        category = "Window Management",
        key = "SUPER + W",
        action_type = "dispatch_float",
        display_key = "Super + W",
        description = "Toggle Floating",
        runnable = false,
    },
    {
        id = "window_cycle_focus",
        priority = 130,
        editable = true,
        category = "Window Management",
        key = "ALT + tab",
        action_type = "dispatch_cycle",
        display_key = "Alt + Tab",
        description = "Cycle Window Focus",
        runnable = false,
    },

    -- Workspaces
    {
        id = "workspaces_switch_1_10",
        priority = 200,
        editable = false,
        category = "Workspaces",
        generator = "workspaces_1_10",
        display_key = "Super + 1 .. 9, 0",
        description = "Workspace 1–10",
        runnable = false,
    },
    {
        id = "workspaces_move_1_10",
        priority = 210,
        editable = false,
        category = "Workspaces",
        generator = "workspaces_move_1_10",
        display_key = "Super + Shift + 1 .. 9, 0",
        description = "Move Window to Workspace 1–10",
        runnable = false,
    },
    {
        id = "workspace_prev",
        priority = 220,
        editable = true,
        category = "Workspaces",
        key = "SUPER + CTRL + left",
        action_type = "focus_workspace_relative",
        workspace = "r-1",
        display_key = "Super + Ctrl + Left",
        description = "Previous Workspace",
        runnable = false,
    },
    {
        id = "workspace_next",
        priority = 230,
        editable = true,
        category = "Workspaces",
        key = "SUPER + CTRL + right",
        action_type = "focus_workspace_relative",
        workspace = "r+1",
        display_key = "Super + Ctrl + Right",
        description = "Next Workspace",
        runnable = false,
    },
    {
        id = "workspace_touchpad_swipe",
        priority = 240,
        editable = false,
        category = "Workspaces",
        action_type = "gesture",
        display_key = "3-Finger Horizontal Swipe",
        description = "Swipe Workspaces (Touchpad)",
        runnable = false,
    },

    -- Window Focus & Resizing
    {
        id = "focus_left",
        priority = 300,
        editable = true,
        category = "Window Focus & Resizing",
        key = "SUPER + left",
        action_type = "focus",
        direction = "left",
        display_key = "Super + Left",
        description = "Focus Window Left",
        runnable = false,
    },
    {
        id = "focus_right",
        priority = 301,
        editable = true,
        category = "Window Focus & Resizing",
        key = "SUPER + right",
        action_type = "focus",
        direction = "right",
        display_key = "Super + Right",
        description = "Focus Window Right",
        runnable = false,
    },
    {
        id = "focus_up",
        priority = 302,
        editable = true,
        category = "Window Focus & Resizing",
        key = "SUPER + up",
        action_type = "focus",
        direction = "up",
        display_key = "Super + Up",
        description = "Focus Window Up",
        runnable = false,
    },
    {
        id = "focus_down",
        priority = 303,
        editable = true,
        category = "Window Focus & Resizing",
        key = "SUPER + down",
        action_type = "focus",
        direction = "down",
        display_key = "Super + Down",
        description = "Focus Window Down",
        runnable = false,
    },
    {
        id = "resize_window_left",
        priority = 310,
        editable = true,
        category = "Window Focus & Resizing",
        key = "SUPER + SHIFT + left",
        action_type = "exec_resize",
        resize_args = "-30 0",
        display_key = "Super + Shift + Left",
        description = "Resize Window Left",
        runnable = false,
    },
    {
        id = "resize_window_right",
        priority = 311,
        editable = true,
        category = "Window Focus & Resizing",
        key = "SUPER + SHIFT + right",
        action_type = "exec_resize",
        resize_args = "30 0",
        display_key = "Super + Shift + Right",
        description = "Resize Window Right",
        runnable = false,
    },
    {
        id = "resize_window_up",
        priority = 312,
        editable = true,
        category = "Window Focus & Resizing",
        key = "SUPER + SHIFT + up",
        action_type = "exec_resize",
        resize_args = "0 -30",
        display_key = "Super + Shift + Up",
        description = "Resize Window Up",
        runnable = false,
    },
    {
        id = "resize_window_down",
        priority = 313,
        editable = true,
        category = "Window Focus & Resizing",
        key = "SUPER + SHIFT + down",
        action_type = "exec_resize",
        resize_args = "0 30",
        display_key = "Super + Shift + Down",
        description = "Resize Window Down",
        runnable = false,
    },

    -- Audio & Media Controls
    {
        id = "volume_raise",
        priority = 400,
        editable = true,
        category = "Audio & Media Controls",
        key = "XF86AudioRaiseVolume",
        action_type = "exec_locked",
        command = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+",
        command_argv = { "wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%+" },
        display_key = "Volume Up Key",
        description = "Volume Up",
        runnable = true,
    },
    {
        id = "volume_lower",
        priority = 401,
        editable = true,
        category = "Audio & Media Controls",
        key = "XF86AudioLowerVolume",
        action_type = "exec_locked",
        command = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-",
        command_argv = { "wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%-" },
        display_key = "Volume Down Key",
        description = "Volume Down",
        runnable = true,
    },
    {
        id = "volume_mute_toggle",
        priority = 402,
        editable = true,
        category = "Audio & Media Controls",
        key = "XF86AudioMute",
        action_type = "exec_locked",
        command = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
        command_argv = { "wpctl", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle" },
        display_key = "Mute Key",
        description = "Toggle Mute",
        runnable = true,
    },
    {
        id = "media_play_pause",
        priority = 410,
        editable = true,
        category = "Audio & Media Controls",
        key = "XF86AudioPlay",
        action_type = "exec_locked",
        command = "playerctl play-pause",
        command_argv = { "playerctl", "play-pause" },
        display_key = "Play / Pause Key",
        description = "Play / Pause",
        runnable = true,
    },
    {
        id = "media_next_track",
        priority = 411,
        editable = true,
        category = "Audio & Media Controls",
        key = "XF86AudioNext",
        action_type = "exec_locked",
        command = "playerctl next",
        command_argv = { "playerctl", "next" },
        display_key = "Next Track Key",
        description = "Next Track",
        runnable = true,
    },
    {
        id = "media_prev_track",
        priority = 412,
        editable = true,
        category = "Audio & Media Controls",
        key = "XF86AudioPrev",
        action_type = "exec_locked",
        command = "playerctl previous",
        command_argv = { "playerctl", "previous" },
        display_key = "Previous Track Key",
        description = "Previous Track",
        runnable = true,
    },

    -- Mouse Controls
    {
        id = "mouse_window_drag",
        priority = 500,
        editable = false,
        category = "Mouse Controls",
        key = "SUPER + mouse:272",
        action_type = "mouse_drag",
        mouse = true,
        display_key = "Super + Left Mouse Drag",
        description = "Move Window (Mouse)",
        runnable = false,
    },
    {
        id = "mouse_window_resize",
        priority = 501,
        editable = false,
        category = "Mouse Controls",
        key = "SUPER + mouse:273",
        action_type = "mouse_resize",
        mouse = true,
        display_key = "Super + Right Mouse Drag",
        description = "Resize Window (Mouse)",
        runnable = false,
    },
}

return M
