#!/usr/bin/env bash

# Standalone Aurelia Shell test runner. The Fedora workstation test runner does
# not load this tree; Aurelia owns its own plugin, backend, and runtime tests.

set -Eeuo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
# shellcheck source=/dev/null
source "$ROOT/tests/test_helper.sh"

run_suite "$ROOT/tests/test_aurelia_shell_plugins.sh"
run_suite "$ROOT/tests/test_plugin_harness.sh"
run_suite "$ROOT/tests/test_manifest_validator.sh"
run_suite "$ROOT/tests/test_plugin_discovery.sh"
run_suite "$ROOT/tests/test_plugin_catalog.sh"
run_suite "$ROOT/tests/test_bar_widget_registry.sh"
run_suite "$ROOT/tests/test_plugin_lifecycle.sh"
run_suite "$ROOT/tests/test_active_bar.sh"
run_suite "$ROOT/tests/test_generic_routing.sh"
run_suite "$ROOT/tests/test_shell_state_migration.sh"
run_suite "$ROOT/tests/test_bar_widget_metadata.sh"
run_suite "$ROOT/tests/test_bar_operations.sh"
run_suite "$ROOT/tests/test_plugin_settings.sh"
run_suite "$ROOT/tests/test_plugin_facades.sh"
run_suite "$ROOT/tests/test_sensitive_service_boundary.sh"
run_suite "$ROOT/tests/test_command_privilege_boundary.sh"
run_suite "$ROOT/tests/test_plugin_clone.sh"
run_suite "$ROOT/tests/test_plugin_lifecycle_management.sh"
run_suite "$ROOT/tests/test_plugin_management.sh"
run_suite "$ROOT/tests/test_plugin_watcher.sh"
run_suite "$ROOT/tests/test_aurelia_menu.sh"
run_suite "$ROOT/tests/test_plugin_migration.sh"
run_suite "$ROOT/tests/test_plugin_survivability.sh"
run_suite "$ROOT/tests/test_shell_reload.sh"
run_suite "$ROOT/tests/test_dev_session.sh"
run_suite "$ROOT/tests/test_keybindings_interaction.sh"
run_suite "$ROOT/tests/test_screenshot_plugins.sh"
run_suite "$ROOT/tests/test_notification_plugins.sh"
run_suite "$ROOT/tests/test_qml_runtime.sh"
run_suite "$ROOT/tests/test_theme_background.sh"
run_suite "$ROOT/tests/test_omarchy_themes.sh"
run_suite "$ROOT/tests/test_image_picker.sh"
run_suite "$ROOT/tests/test_bar_widgets.sh"
run_suite "$ROOT/tests/test_workspace_switcher.sh"
run_suite "$ROOT/tests/test_bluetooth_plugin.sh"
run_suite "$ROOT/tests/test_calendar_surface.sh"
run_suite "$ROOT/tests/test_display_plugin.sh"
run_suite "$ROOT/tests/test_network_plugin.sh"
run_suite "$ROOT/tests/test_network_qml_runtime.sh"
run_suite "$ROOT/tests/test_network_dns_runtime.sh"
run_suite "$ROOT/tests/test_launcher_plugin.sh"
run_suite "$ROOT/tests/test_command_center_backend.sh"
run_suite "$ROOT/tests/test_package_manager_backend.sh"
run_suite "$ROOT/tests/test_aurelia_provider.sh"
run_suite "$ROOT/tests/test_updates_backend.sh"
run_suite "$ROOT/tests/test_about_backend.sh"
run_suite "$ROOT/tests/test_about_branding.sh"
run_suite "$ROOT/tests/test_transcode_ascii.sh"
run_suite "$ROOT/tests/test_hyprland_provider.sh"

print_test_summary
